### ISSUE TITLE
About code for plotting

### ISSUE THREAD

**Issue by ClaireGyn** [srouchier/buildingenergygeeks#2]
Hi Simon Rouchier,

Sorry to bother you. May I ask how you made this graph as attached below using R ? I think it's quite nice and fit my need but I didn't find the corresponding code for plotting it in this repo. Could I ask whether the code is available?

Looking forward to your reply. Thank you very much! Have a nice day.

![屏幕截图 2021-08-22 223416](https://user-images.githubusercontent.com/34539124/130359038-b4ebb070-a8d8-4349-9ec7-92e48b2b0f84.png)

**Comment by srouchier** [comment]
Hello,
I didn't include the code in the repo as it is just an illustration of prior/posterior in the theoretical chapter, but here is the complete code I used:

```
library(ggplot2)

dat1 <- data.frame(distribution = factor(rep(c("prior","posterior"), each=100000)), 
                   set_point = c(rnorm(100000, mean=20, sd=5),rnorm(100000, mean=23, sd=2)))

ggplot(dat1, aes(x=set_point, fill=distribution)) +
  geom_density(alpha=.3) +
  geom_vline(aes(xintercept=24),   # Ignore NA values for mean
             color="black", linetype="dashed", size=1) +
  theme_gray(base_size=25)
```

There are probably more efficient ways to do it
